import { CardDefinition } from "../entity/card";

export const CARD_LIST: CardDefinition[] = [
  { id: "clubs_2", name: "2 of Clubs", texture: "Clubs_2.png", value: 2, is_special: 0, special_effect: 0 },
  { id: "clubs_3", name: "3 of Clubs", texture: "Clubs_3.png", value: 3, is_special: 0, special_effect: 0 },
  { id: "clubs_4", name: "4 of Clubs", texture: "Clubs_4.png", value: 4, is_special: 0, special_effect: 0 },
  { id: "clubs_5", name: "5 of Clubs", texture: "Clubs_5.png", value: 5, is_special: 0, special_effect: 0 },
  { id: "clubs_6", name: "6 of Clubs", texture: "Clubs_6.png", value: 6, is_special: 0, special_effect: 0 },
  { id: "clubs_7", name: "7 of Clubs", texture: "Clubs_7.png", value: 7, is_special: 0, special_effect: 0 },
  { id: "clubs_8", name: "8 of Clubs", texture: "Clubs_8.png", value: 8, is_special: 0, special_effect: 0 },
  { id: "clubs_9", name: "9 of Clubs", texture: "Clubs_9.png", value: 9, is_special: 0, special_effect: 0 },
  { id: "clubs_10", name: "10 of Clubs", texture: "Clubs_10.png", value: 10, is_special: 0, special_effect: 0 },
  { id: "clubs_ace", name: "Ace of Clubs", texture: "Clubs_ACE.png", value: 11, is_special: 0, special_effect: 0 },
  { id: "clubs_j", name: "Jack of Clubs", texture: "Clubs_J.png", value: 12, is_special: 1, special_effect: 1 },
  { id: "clubs_q", name: "Queen of Clubs", texture: "Clubs_Q.png", value: 13, is_special: 1, special_effect: 2 },
  { id: "clubs_k", name: "King of Clubs", texture: "Clubs_K.png", value: 14, is_special: 1, special_effect: 3 },

  { id: "diamonds_2", name: "2 of Diamonds", texture: "Diamonds_2.png", value: 2, is_special: 0, special_effect: 0 },
  { id: "diamonds_3", name: "3 of Diamonds", texture: "Diamonds_3.png", value: 3, is_special: 0, special_effect: 0 },
  { id: "diamonds_4", name: "4 of Diamonds", texture: "Diamonds_4.png", value: 4, is_special: 0, special_effect: 0 },
  { id: "diamonds_5", name: "5 of Diamonds", texture: "Diamonds_5.png", value: 5, is_special: 0, special_effect: 0 },
  { id: "diamonds_6", name: "6 of Diamonds", texture: "Diamonds_6.png", value: 6, is_special: 0, special_effect: 0 },
  { id: "diamonds_7", name: "7 of Diamonds", texture: "Diamonds_7.png", value: 7, is_special: 0, special_effect: 0 },
  { id: "diamonds_8", name: "8 of Diamonds", texture: "Diamonds_8.png", value: 8, is_special: 0, special_effect: 0 },
  { id: "diamonds_9", name: "9 of Diamonds", texture: "Diamonds_9.png", value: 9, is_special: 0, special_effect: 0 },
  {
    id: "diamonds_10",
    name: "10 of Diamonds",
    texture: "Diamonds_10.png",
    value: 10,
    is_special: 0,
    special_effect: 0,
  },
  {
    id: "diamonds_ace",
    name: "Ace of Diamonds",
    texture: "Diamonds_ACE.png",
    value: 11,
    is_special: 0,
    special_effect: 0,
  },
  {
    id: "diamonds_j",
    name: "Jack of Diamonds",
    texture: "Diamonds_J.png",
    value: 12,
    is_special: 1,
    special_effect: 1,
  },
  {
    id: "diamonds_q",
    name: "Queen of Diamonds",
    texture: "Diamonds_Q.png",
    value: 13,
    is_special: 1,
    special_effect: 2,
  },
  {
    id: "diamonds_k",
    name: "King of Diamonds",
    texture: "Diamonds_K.png",
    value: 14,
    is_special: 1,
    special_effect: 3,
  },

  { id: "hearts_2", name: "2 of Hearts", texture: "Hearts_2.png", value: 2, is_special: 0, special_effect: 0 },
  { id: "hearts_3", name: "3 of Hearts", texture: "Hearts_3.png", value: 3, is_special: 0, special_effect: 0 },
  { id: "hearts_4", name: "4 of Hearts", texture: "Hearts_4.png", value: 4, is_special: 0, special_effect: 0 },
  { id: "hearts_5", name: "5 of Hearts", texture: "Hearts_5.png", value: 5, is_special: 0, special_effect: 0 },
  { id: "hearts_6", name: "6 of Hearts", texture: "Hearts_6.png", value: 6, is_special: 0, special_effect: 0 },
  { id: "hearts_7", name: "7 of Hearts", texture: "Hearts_7.png", value: 7, is_special: 0, special_effect: 0 },
  { id: "hearts_8", name: "8 of Hearts", texture: "Hearts_8.png", value: 8, is_special: 0, special_effect: 0 },
  { id: "hearts_9", name: "9 of Hearts", texture: "Hearts_9.png", value: 9, is_special: 0, special_effect: 0 },
  { id: "hearts_10", name: "10 of Hearts", texture: "Hearts_10.png", value: 10, is_special: 0, special_effect: 0 },
  { id: "hearts_ace", name: "Ace of Hearts", texture: "Hearts_ACE.png", value: 11, is_special: 0, special_effect: 0 },
  { id: "hearts_j", name: "Jack of Hearts", texture: "Hearts_J.png", value: 12, is_special: 1, special_effect: 1 },
  { id: "hearts_q", name: "Queen of Hearts", texture: "Hearts_Q.png", value: 13, is_special: 1, special_effect: 2 },
  { id: "hearts_k", name: "King of Hearts", texture: "Hearts_K.png", value: 14, is_special: 1, special_effect: 3 },

  { id: "spades_2", name: "2 of Spades", texture: "Spades_2.png", value: 2, is_special: 0, special_effect: 0 },
  { id: "spades_3", name: "3 of Spades", texture: "Spades_3.png", value: 3, is_special: 0, special_effect: 0 },
  { id: "spades_4", name: "4 of Spades", texture: "Spades_4.png", value: 4, is_special: 0, special_effect: 0 },
  { id: "spades_5", name: "5 of Spades", texture: "Spades_5.png", value: 5, is_special: 0, special_effect: 0 },
  { id: "spades_6", name: "6 of Spades", texture: "Spades_6.png", value: 6, is_special: 0, special_effect: 0 },
  { id: "spades_7", name: "7 of Spades", texture: "Spades_7.png", value: 7, is_special: 0, special_effect: 0 },
  { id: "spades_8", name: "8 of Spades", texture: "Spades_8.png", value: 8, is_special: 0, special_effect: 0 },
  { id: "spades_9", name: "9 of Spades", texture: "Spades_9.png", value: 9, is_special: 0, special_effect: 0 },
  { id: "spades_10", name: "10 of Spades", texture: "Spades_10.png", value: 10, is_special: 0, special_effect: 0 },
  { id: "spades_ace", name: "Ace of Spades", texture: "Spades_ACE.png", value: 11, is_special: 0, special_effect: 0 },
  { id: "spades_j", name: "Jack of Spades", texture: "Spades_J.png", value: 12, is_special: 1, special_effect: 1 },
  { id: "spades_q", name: "Queen of Spades", texture: "Spades_Q.png", value: 13, is_special: 1, special_effect: 2 },
  { id: "spades_k", name: "King of Spades", texture: "Spades_K.png", value: 14, is_special: 1, special_effect: 3 },

  { id: "joker_red", name: "Red Joker", texture: "Joker_1.png", value: 15, is_special: 1, special_effect: 4 },
  { id: "joker_black", name: "Black Joker", texture: "Joker_2.png", value: 15, is_special: 1, special_effect: 5 },
];
